// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:da5dfb64-7ad9-4eec-9ba2-c9a0728e2440',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'mentormatchingapp-hosting-mobilehub-167547329',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2pznhds7goox5.cloudfront.net',
    'aws_mobile_analytics_app_id': '9eafb503e50e46d1924984a331035517',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '051fa8cd-daba-4f0c-8093-c69fc9630388',
    'aws_project_name': 'Mentor_Matching_App-2018-05-05-11-20-06',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'mentormatchingapp-mobilehub-167547329',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_hbf109V9H',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7ug9l1opt18t1sd0kdlodjndvd',
}

export default awsmobile;
